Repository fga-eps-mds/2019.2-ArBC-API, pull requests merged in 2019-10, with the labels that each got.

#13 Configurar Integração Contínua
  .gitlab-ci.yml
  api/settings.py
  app/models.py
  app/tests.py
  compose/local/django/Dockerfile
  pytest.ini
Labels: EPS, devops

#16 Testes Quebrando
  app/serializers.py
  app/tests.py
  app/views.py
Labels: MDS, bug, technical

#19 Corrigir os URLs das Imagens Enviadas
  api/urls.py
  app/urls.py
Labels: MDS, bug, technical

#20 Remoção automática das imagens
  api/settings.py
  app/models.py
  app/tests.py
Labels: MDS, enhancement, technical

#14 Adicionar CORS header
  api/settings.py
Labels: MDS, technical

#18 Popular banco de dados
  README.md
  seed.py
  seeds/A.gif
  seeds/B.gif
  seeds/C.gif
  seeds/D.gif
  seeds/E.gif
  seeds/F.gif
  seeds/G.gif
  seeds/H.gif
  seeds/I.gif
  seeds/J.gif
  seeds/K.gif
  seeds/L.gif
  seeds/M.gif
  seeds/N.gif
  seeds/O.gif
  seeds/P.gif
  seeds/Q.gif
  seeds/R.gif
  seeds/S.gif
  seeds/T.gif
  seeds/U.gif
  seeds/V.gif
  seeds/W.gif
  seeds/X.gif
  seeds/Y.gif
  seeds/Z.gif
Labels: MDS, technical

#22 Respostas das requisições estão paginadas
  api/settings.py
Labels: MDS, bug, technical
