Repository fga-eps-mds/2019.2-ArBC-API, pull requests merged in 2019-11, with the labels that each got.

#28 Revertendo patterns no back
  app/admin.py
  app/models.py
  app/serializers.py
  app/tests.py
  app/urls.py
  app/views.py
  seeds.py
  seeds_patts/pattern-A1.patt
  seeds_patts/pattern-A2.patt
  seeds_patts/pattern-B1.patt
  seeds_patts/pattern-B2.patt
  seeds_patts/pattern-C1.patt
  seeds_patts/pattern-C2.patt
  seeds_patts/pattern-D1.patt
  seeds_patts/pattern-D2.patt
  seeds_patts/pattern-E1.patt
  seeds_patts/pattern-E2.patt
  seeds_patts/pattern-F1.patt
  seeds_patts/pattern-F2.patt
  seeds_patts/pattern-G1.patt
  seeds_patts/pattern-G2.patt
  seeds_patts/pattern-H1.patt
  seeds_patts/pattern-H2.patt
  seeds_patts/pattern-I1.patt
  seeds_patts/pattern-I2.patt
  seeds_patts/pattern-J1.patt
  seeds_patts/pattern-J2.patt
  seeds_patts/pattern-K1.patt
  seeds_patts/pattern-K2.patt
  seeds_patts/pattern-L1.patt
  seeds_patts/pattern-L2.patt
  seeds_patts/pattern-M1.patt
  seeds_patts/pattern-M2.patt
  seeds_patts/pattern-N1.patt
  seeds_patts/pattern-N2.patt
  seeds_patts/pattern-O1.patt
  seeds_patts/pattern-O2.patt
  seeds_patts/pattern-P1.patt
  seeds_patts/pattern-P2.patt
  seeds_patts/pattern-Q1.patt
  seeds_patts/pattern-Q2.patt
  seeds_patts/pattern-R1.patt
  seeds_patts/pattern-R2.patt
  seeds_patts/pattern-S1.patt
  seeds_patts/pattern-S2.patt
  seeds_patts/pattern-T1.patt
  seeds_patts/pattern-T2.patt
  seeds_patts/pattern-U1.patt
  seeds_patts/pattern-U2.patt
  seeds_patts/pattern-V1.patt
  seeds_patts/pattern-V2.patt
  seeds_patts/pattern-W1.patt
  seeds_patts/pattern-W2.patt
  seeds_patts/pattern-X1.patt
  seeds_patts/pattern-X2.patt
  seeds_patts/pattern-Y1.patt
  seeds_patts/pattern-Y2.patt
  seeds_patts/pattern-Z1.patt
  seeds_patts/pattern-Z2.patt
Labels: MDS, bug

#30 Tornar a API acessível localmente em ambiente de desenvolvimento
  api/settings.py
  release-tasks.sh
Labels: MDS, technical

#34 Update pipeline
  .gitlab-ci.yml
Labels: EPS, devops
